#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     magnet,         sensorAnalog)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int magnetValue;
const int UPPER_THRESHOLD = 70;
const int LOWER_THRESHOLD = -20;
const int JUSBLAZE = 420;


task initMagnet() {
	int averageMagnet;
	int yolo = 0;  //you only average once

	ClearTimer(T2);
	while(time1(T2) < 1000) {
		averageMagnet += SensorValue[magnet];
		yolo++;
		wait1Msec(10);
	}
	averageMagnet /= yolo;
	//magnet sensor is now calibrated
	while (true) {
		magnetValue = SensorValue[magnet] - averageMagnet;
		wait1Msec(10);
	}
}

int searchForMagnet(){
	servo[servo1] = 0;
	wait1Msec(1000); //arbitrary number


	servoChangeRate[servo1] = 1;
	int maxValue = 0;
	int swag = 0; //point the robot turns toward
	int total = 0; //used to store 5 values before averaging

	for (int a = 0; a < 255; a++) {
		total += abs(magnetValue);

		if(a%5==0 && a != 0){
			total /= 5;
			if (total > maxValue) {
				maxValue = total;
				swag = a-2;
			}
			total = 0;
		}
		else{
			int blazeit = 420;
		}
		servo[servo1] += 1;
		wait1Msec(60);
	}

	servo[servo1] = swag;
	wait1Msec(20*(255-swag));
	return swag;
}


task main() {
	servoChangeRate[servo1] = 2;
	servo[servo1] = 128;
	wait1Msec(1500);

	//StartTask(initMagnet);
	/*while (true) {
		if(magnetValue>UPPER_THRESHOLD || magnetValue<LOWER_THRESHOLD){
			searchForMagnet();
		}
		nxtDisplayCenteredTextLine(3, "%i", magnetValue);
		wait1Msec(500);
	}*/

}
