#pragma config(Sensor, S1,     magnet,         sensorAnalog)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int magnetValue;

task init_magnet() {
	int averageMagnet;
	int yolo = 0;

	ClearTimer(T2);
	while(time1(T2) < 1000) {
		averageMagnet += SensorValue[magnet];
		yolo++;
		wait1Msec(10);
	}
	averageMagnet /= yolo;

	while (true) {
		magnetValue = SensorValue[magnet] - averageMagnet;
		wait1Msec(10);
	}
}

task main() {
	StartTask(init_magnet);
	wait1Msec(1500);

	while (true) {
		nxtDisplayCenteredTextLine(3, "%i", magnetValue);
		wait1Msec(500);
	}
}
