#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     magnetic,       sensorAnalog)
#pragma config(Sensor, S3,     sonar,          sensorSONAR)
#pragma config(Sensor, S4,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "headers/gyro.h"
#include "headers/movementOmni.h"
#include "headers/bluetooth.h"

task debug()
{
	while (true)
	{
		nxtDisplayCenteredTextLine(2, "Front: %i", sonarValue[front]);
		nxtDisplayCenteredTextLine(3, "Back: %i", sonarValue[back]);
		nxtDisplayCenteredTextLine(4, "Left: %i", sonarValue[left]);
		nxtDisplayCenteredTextLine(5, "Right: %i", sonarValue[right]);
		nxtDisplayCenteredTextLine(6, "Angle: %.2f", angle);
		wait1Msec(100);
	}
}


task main()
{
	StartTask(updateGyro);
	StartTask(SendAck);
	StartTask(debug);
	while(true)
		wait10Msec(1000);
}
