#pragma config(Sensor, S1,     left,           sensorSONAR)
#pragma config(Sensor, S2,     back,           sensorSONAR)
#pragma config(Sensor, S3,     right,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task commLink()
{
	bBTSkipPswdPrompt = true;
    setBluetoothVisibility(true);
	bBTHasProgressSounds = true; //make alert noises
	setBluetoothOn();
	while (bBTBusy)
	{
		wait1Msec(1000);
	}
	string name = "Manager";
    setFriendlyName(name);

	bool linked = false;
	while (!linked)  //basic link ack
	{
		if (message == 0)
		{
			ClearMessage();
			wait1Msec(10);
		}
		else if (message == 42)
		{
			wait1Msec(50);
			sendMessage(314);
			linked = true;
		}
	}

	while (true)
	{
		sendMessageWithParm(SensorValue[left], SensorValue[back], SensorValue[right]);
		wait10Msec(100);
	}
}

task main()
{
	StartTask(commLink);
	while (true)
		wait1Msec(1000);
}
