#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     drive,         tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

long target;
task PID();
bool aligned;
float rate;

task main()
{
	nMotorEncoder[drive] = 0;
	StartTask(PID);
	target = -7200;
	while (!aligned)
		wait1Msec(100);
	StopTask(PID);
}

task PID()
{
	float prevErrorTime;
	float prevError;
	float errorTime;
	float error;
	float kP = .03;
	float kI;
	float kD = .5;
	aligned = false;
	time1[T1] = 0;
	while(true)
	{
		prevErrorTime = errorTime;
		prevError = error;
		errorTime = time1[T1];
		error = target - nMotorEncoder[drive];
		rate = (error - prevError)/(errorTime - prevErrorTime);
		if (abs(error) > 15 || abs(rate) > 10)
		{
			motor[drive] = kP * error + kD * rate;
			aligned = false;
		}
		else
			aligned = true;
		wait1Msec(100);
	}
}
