#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     slide,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    release,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	const int fwd =	-50;
	const int back = 50;
	const int encoderFwd = 50;
	bool isInMenu = true;
	int distance = 0;
	while(isInMenu){
		nxtDisplayCenteredTextLine(3, "Distance: %i", distance);
		if(nNxtButtonPressed == 1){
		 distance+=600;
		}
		else if(nNxtButtonPressed == 2){
			distance-=600;
		}
		else if(nNxtButtonPressed == 3){
			nxtDisplayCenteredTextLine(3, "LAUNCHING!!!");
			wait1Msec(2000);
			isInMenu = false;
		}
		wait1Msec(250);
	}
	if(distance < 0){
		nxtDisplayCenteredTextLine(3, "Distance is less than 0");
		wait1Msec(2000);
		return;
	}

	while(SensorValue(touch) == 0){
		motor[slide]=fwd;

	}
	motor[slide]=0;
	wait1Msec(3000);
	servo[release] = 100;
	wait1Msec(500);
	nMotorEncoder[slide] = 0;
	while(nMotorEncoder[slide] < distance)
	{
		nxtDisplayCenteredTextLine(3, "Encoder: %i", nMotorEncoder[slide]);
		if(distance>distance/2){ //slows down as approaches target
	  	motor[slide] = back;
		}
		else{
			motor[slide] = back-28;
		}
	}

	motor[slide] = 0;
	servo[release] = 255;
	wait1Msec(2000); //fires a flaming ball of fire
//reset
	servo[release] = 100;
	wait1Msec(500);

	while(SensorValue(touch) == 0){
		if((encoderFwd-(nMotorEncoder[slide]) > distance/2)){ //slows down as approaches target
	  	motor[slide] = fwd;
		}
		else{
			motor[slide] = fwd+28;
		}

	}
	motor[slide] = 0;
	motor[slide] = 20;


}
