#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     slide,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    release,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	const int fwd = -50;
	const int back = 50;

	servo[release] = 100;
	wait1Msec(2000);
	nMotorEncoder[slide] = 0;
	while(nMotorEncoder[slide] < 720)
	{
	  motor[slide] = fwd;

	}
	motor[slide] = 0;
	servo[release] = 240;
	wait1Msec(2000); //fires a flaming ball of fire
//reset
	servo[release] = 100;
	wait1Msec(500);
	nMotorEncoder[slide] = 0;
	while(nMotorEncoder[slide] > -720)
	{
	  motor[slide] = back;
	}
	motor[slide] = 0;

}
