#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     magnetic,       sensorAnalog)
#pragma config(Sensor, S3,     sonar,          sensorSONAR)
#pragma config(Sensor, S4,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "include/gyro.h"
#include "include/movementOmni.h"


const int right;
const int front;
const int left;

task wander()
{
	while(true)
	{
		if (SensorValue[sonar] < 255)
			StartTask(investigate);
	}
}

task investigate()
{
	9
}

task debug()
{
	while (true)
	{
		nxtDisplayCenteredTextLine(3, "Distance: %i", SensorValue[sonar]);
		nxtDisplayCenteredTextLine(4, "Angle: %.2f", angle);
		wait1Msec(100);
	}
}

task main()
{
	StartTask(debug);
	StartTask(updateGyro);
	StartTask(wander);
	while(true)
		wait10Msec(1000);
}
