#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     magnetic,       sensorAnalog)
#pragma config(Sensor, S3,     sonar,          sensorSONAR)
#pragma config(Sensor, S4,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "headers/gyro.h"
#include "headers/movementOmni.h"

int sonarValue[4];

const int left = 0;
const int back = 1;
const int right = 2;
const int front = 3;

task investigate()
{
}

task wander()
{
	while(true)
	{
		if (SensorValue[sonar] < 255)
			StartTask(investigate);
	}
}

task commLink()
{
	bBTSkipPswdPrompt = true;
	bBTHasProgressSounds = true; //make alert noises
	setBluetoothOn();
	string name = "Driver";
    setFriendlyName(name);
	btSearch();
	while (bBTBusy) //hopefully this variable can tell if the nxt is searching for devices
	{
		wait1Msec(1000);
	}
	btConnect(1, "Manager"); //try to connect to the other NXT
	while (bBTBusy)
	{
		wait1Msec(1000);
	}


	bool linked = false;
	while (!linked)
	{
		sendMessage(42);
		while (true)
		{
			if (message == 0)
				ClearMessage();
			else
				break;
			wait1Msec(50);
		}
		if (message == 314)
			linked = true;
		wait1Msec(1000);
	}

	while (true) //main loop that reads messages from the other NXT
	{
		word temp;
		while (bQueuedMsgAvailable()) //empty queue to get latest message
		{
			ClearMessage();
			temp = message;
		}
		if (message == 0)
		{
			ClearMessage();
			wait1Msec(10);
		}
		else
		{
			sonarValue[back] = messageParm[back];
			sonarValue[right] = messageParm[right];
			sonarValue[left] = messageParm[left];
			ClearMessage();
			wait1Msec(10);
		}
	}


}

task debug()
{
	while (true)
	{
		nxtDisplayCenteredTextLine(3, "Distance: %i", SensorValue[sonar]);
		nxtDisplayCenteredTextLine(4, "Angle: %.2f", angle);
		wait1Msec(100);
	}
}

task main()
{
	StartTask(debug);
	StartTask(updateGyro);
	StartTask(commLink);
	while(true)
		wait10Msec(1000);
}
