#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,     color,          sensorNone)
#pragma config(Sensor, S3,     gyro,           sensorNone)
#pragma config(Sensor, S4,     ir,             sensorNone)
#pragma config(Motor,  motorA,           ,             tmotorNXT, PIDControl)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorFL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorFS,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servoL,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servoR,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{

	waitForStart();

	while(true)                            // Infinite loop:
	{
		getJoystickSettings(joystick); //update joystick values


		//movement
		if (abs(joystick.joy1_y1) > 35)
		{
			//Left motors mapped to joystick 1
			motor[motorFL] = -joystick.joy1_y1;
			motor[motorBL] = -joystick.joy1_y1;
		}
		else
		{
			motor[motorFL] = 0;
			motor[motorBL] = 0;
		}

		if (abs(joystick.joy1_y2) > 35)
		{
			//right motors mapped to joystick 2
			motor[motorFR] = -joystick.joy1_y2;
			motor[motorBR] = -joystick.joy1_y2;
		}
		else
		{
			motor[motorFR] = 0;
			motor[motorBR] = 0;
		}

		//flag raiser
		if (joy1Btn(1))
			motor[motorFS] = -80;
		else if (joy1Btn(3))
			motor[motorFS] = 80;
		else
			motor[motorFS] = 0;

		//hopper
		if (joy2Btn(6))
			motor[motorH] = -100;
		else if (joy2Btn(8))
			motor[motorH] = 50;
		else
			motor[motorH] = 0;


	}
}
