#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ir,             sensorI2CCustom)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     color,          sensorCOLORFULL)
#pragma config(Motor,  motorA,           ,             tmotorNXT, PIDControl)
#pragma config(Motor,  motorB,          blockMotor,    tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorBL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorFL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorFlag,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorLift,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorFlywheel, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorL,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* ASCI Generated by Kieran :D */
/*
 			   										   	  _______________________
                                                         /\  ___________________ \
                                                         \ \ \_________________/\ \
  _____       _____      __      __________    _______    \ \ \         __     \ \ \     __________    _____     _______     ________
 /\  __ \    /\  __\    /\ \    /\____  ___\  /\  ___ \    \ \ \       / \\     \ \ \   /\____  ___\  /\  __\   /\  ___ \   /\   \   \
 \ \ \ \ \   \ \ \_/    \ \ \   \/___/\ \__/  \ \ \_/\ \    \ \ \      \ \  \    \ \ \  \/___/\ \__/  \ \ \_/   \ \ \_/\ \  \ \ \ \ \ \
  \ \ \ \ \   \ \ \__    \ \ \       \ \ \     \ \ \\_\ \    \ \ \     \ \ __ \   \ \ \      \ \ \     \ \ \__   \ \ \\_\ \  \ \ \___\ \
   \ \ \ \ \   \ \  _\    \ \ \       \ \ \     \ \  ___ \    \ \ \    \ \ \/\  \  \ \ \      \ \ \     \ \  _\   \ \  __  \  \ \ \__/\ \
    \ \ \_\ \   \ \ \/__   \ \ \___    \ \ \     \ \ \_/\ \    \ \ \   \ \ \_\_\  \ \ \ \      \ \ \     \ \ \/__  \ \ \_/\ \  \ \ \ \ \ \
     \ \____/    \ \____\   \ \____\    \ \_\     \ \_\\ \_\  	\ \ \  \ \__________\\ \ \      \ \_\     \ \____\  \ \_\\ \_\  \ \_\ \ \_\
      \/___/      \/____/    \/____/     \/_/      \/_/ \/_/     \ \ \ \/__________/  \ \ \      \/_/      \/____/   \/_/ \/_/   \/_/  \/_/
                                                                  \ \ \________________\_\ \
                         	     				   				   \ \______________________\
  																	\/______________________/

*/
#include "JoystickDriver.c"
#include "..\headers\gyro.h"
#include "..\headers\servo.h"
#include "..\headers\ir.h"
#include "..\headers\movementTank.h"
//#include "headers\movementOmni.h"
#include "..\headers\color.h"

void init()
{
	StartTask(updateGyro);
	StartTask(updateIR);
	wait1Msec(300);
}

task main()
{
	waitForStart();
	init();
	int time;

	// moving till IR
	ClearTimer(T2);
	move(50);
	while(getZone() != 2){
		if (time1(T2) > 4000) {
			move(0);
		}
		else if(getZone()==3){
			move(30);
		}
	}
	move(0);
	if (time1(T2) > 1500) {
		time = time1(T2);
	}
	else {
		move(30);
		wait1Msec(450);
		move(0);
		time = time1(T2);
	}

	//put block
	motor[blockMotor] = 100;
	wait1Msec(800);
	motor[blockMotor] = -100;
	wait1Msec(700);

	//retracing steps
	move(-70);
	wait1Msec(time);
	move(0);

	turn(90);

	ClearTimer(T2);
	/*while(getColor()!=WHITE){
		if (time1(T2) < 3000)
			move(-70);
		else
			move(0);
  }
  move(50);
  wait1Msec(300);*/
  move(-70);
  wait1Msec(1500);
  move(0);
	turn(-90);
	move(70);
	wait1Msec(1300);

}
